
import { Spirit, Batch, Operation, Report } from './types';

// Initial mock data
export const INITIAL_MOCK_SPIRITS: Spirit[] = [
  {
    id: '1',
    name: 'Mountain Rye Whiskey',
    type: 'whiskey',
    defaultProof: 90,
    description: 'Our signature rye whiskey with notes of vanilla and oak',
    active: true,
    createdAt: new Date('2023-01-15'),
  },
  {
    id: '2',
    name: 'Peak Vodka',
    type: 'vodka',
    defaultProof: 80,
    description: 'Smooth wheat vodka, triple distilled',
    active: true,
    createdAt: new Date('2023-02-20'),
  },
  {
    id: '3',
    name: 'Alpine Gin',
    type: 'gin',
    defaultProof: 94,
    description: 'Botanical gin with notes of juniper and local herbs',
    active: true,
    createdAt: new Date('2023-03-10'),
  },
];

export const INITIAL_MOCK_BATCHES: Batch[] = [
  {
    id: '1',
    spiritId: '1',
    batchNumber: 'RW-2023-001',
    productionDate: new Date('2023-04-05'),
    proof: 90,
    originalLiters: 400,
    currentLiters: 385,
    status: 'aging',
    notes: 'Aging in charred oak barrels',
    createdAt: new Date('2023-04-05'),
  },
  {
    id: '2',
    spiritId: '2',
    batchNumber: 'PV-2023-001',
    productionDate: new Date('2023-04-15'),
    proof: 80,
    originalLiters: 600,
    currentLiters: 550,
    status: 'ready_for_bottling',
    createdAt: new Date('2023-04-15'),
  },
  {
    id: '3',
    spiritId: '3',
    batchNumber: 'AG-2023-001',
    productionDate: new Date('2023-05-01'),
    proof: 94,
    originalLiters: 300,
    currentLiters: 300,
    status: 'in_production',
    createdAt: new Date('2023-05-01'),
  },
];

export const INITIAL_MOCK_OPERATIONS: Operation[] = [
  {
    id: '1',
    type: 'production',
    date: new Date('2023-04-05'),
    spiritId: '1',
    batchId: '1',
    proof: 90,
    liters: 400,
    proofGallons: 95.1,
    notes: 'Initial distillation run for 2023',
    operatorId: '1',
    createdAt: new Date('2023-04-05'),
  },
  {
    id: '2',
    type: 'production',
    date: new Date('2023-04-15'),
    spiritId: '2',
    batchId: '2',
    proof: 80,
    liters: 600,
    proofGallons: 126.8,
    notes: 'Standard vodka run',
    operatorId: '1',
    createdAt: new Date('2023-04-15'),
  },
  {
    id: '3',
    type: 'loss',
    date: new Date('2023-04-30'),
    spiritId: '2',
    batchId: '2',
    proof: 80,
    liters: 50,
    proofGallons: 10.6,
    notes: 'Evaporation and sampling',
    operatorId: '2',
    createdAt: new Date('2023-04-30'),
  },
  {
    id: '4',
    type: 'production',
    date: new Date('2023-05-01'),
    spiritId: '3',
    batchId: '3',
    proof: 94,
    liters: 300,
    proofGallons: 74.6,
    notes: 'New gin recipe',
    operatorId: '2',
    createdAt: new Date('2023-05-01'),
  },
  {
    id: '5',
    type: 'bottling',
    date: new Date('2023-05-15'),
    spiritId: '1',
    batchId: '1',
    proof: 90,
    liters: 15,
    proofGallons: 3.6,
    bottles: 20,
    bottleSize: '750ml',
    notes: 'Small test bottling run',
    operatorId: '1',
    createdAt: new Date('2023-05-15'),
  },
];

export const INITIAL_MOCK_REPORTS: Report[] = [
  {
    id: '1',
    type: 'form_5110_40',
    period: '2023-04',
    status: 'submitted',
    submittedAt: new Date('2023-05-15'),
    data: {
      totalProduction: 221.9,
      totalWithdrawal: 3.6,
      totalLoss: 10.6,
    },
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2023-05-15'),
  },
];
