// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scvxzkmfellyrrmxhzqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjdnh6a21mZWxseXJybXhoenFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTQ0MzYsImV4cCI6MjA2ODM3MDQzNn0.hpyO1d3ILWKQ9dYRUzyDDGfv6CYxWk8F2twW2NGbeDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});